project:
  type: website
  output-dir: docs
  

website:
  title: "Hello World"
  navbar:
    left:
      - about.qmd
      - publications.qmd
      - icon: github
        href: https://github.com/jmbuhr
format:
  html:
    mainfont: Roboto
    theme:
      light:
        - cosmo
        - custom.scss
      dark:
        - darkly
    css: styles.css


bibliography: references.bib

